defmodule Todopoc.Repo.Migrations.SimplifyTodos do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_sqlite.generate_migrations`
  """

  use Ecto.Migration

  def up do
    create table(:todos, primary_key: false) do
      add :updated_at, :utc_datetime_usec, null: false
      add :inserted_at, :utc_datetime_usec, null: false
      add :user_id, :bigint, null: false
      add :due_date, :date
      add :status, :text, null: false
      add :description, :text
      add :title, :text, null: false
      add :id, :bigserial, null: false, primary_key: true
    end
  end

  def down do
    drop table(:todos)
  end
end